### ISSUE TITLE
Dagger 0.2 Migration Roadmap

### ISSUE THREAD

**Issue by hongchaodeng** [h8r-dev/heighliner#49]
- [x] initNocalhostData (@yuyicai )
- [x] getIngressVersion (@hongchaodeng)
- [x] createH8rIngress (@yuyicai )
- [x] installIngress (@lyzhang1999 )
- [x] installNocalhost -> createH8rIngress (@yuyicai)
- [x] installArgoCD -> installIngress, createH8rIngress (@lyzhang1999)
- [x] installPrometheusStack -> installIngress, createH8rIngress (@lyzhang1999)
- [x] installLokiStack -> installIngress (@lyzhang1999)
- [x] kubectlApply (@yuyicai )
- [x] getIngressIP (@lyzhang1999 )
